In [1]:
#Input Array
Input=[
    [1,0,1],
    [1,1,1],
    [0,0,1],
]

In [2]:
#Output Array
Output=[
    [1],
    [1],
    [0],
]

In [3]:
import numpy as np

In [4]:
np.random.seed(42)

In [5]:
X = np.array(Input)
y = np.array(Output)

In [6]:
X.shape, y.shape

((3, 3), (3, 1))

![../notebooks/images/title](../notebooks/images/graph.jpg)

In [7]:
# Define the number of neurons at input hidden and output layer
# Weights initialization for edges between input and hidden layer
# bias for hidden layer neurons
# Weights initialization for edges between hidden and output layer
# bias for output layer neuron(s)
# Define activation function for hidden layer and output layer neurons
# Define derivative of activation function for hidden and output layer neurons
# Forward Propagation
# Backward Propagation
# Train for more number of epochs

In [8]:
inputlayer_neurons = 3
hiddenlayer_neurons = 2
outputlayer_neuron = 1

In [9]:
wih = np.round(np.random.uniform(size=(inputlayer_neurons, hiddenlayer_neurons)), decimals=1)

In [10]:
wih

array([[0.4, 1. ],
       [0.7, 0.6],
       [0.2, 0.2]])

In [11]:
bih = np.round(np.random.uniform(size=(1, hiddenlayer_neurons)), decimals=1)

In [12]:
bih

array([[0.1, 0.9]])

In [13]:
who = np.round(np.random.uniform(size=(hiddenlayer_neurons, outputlayer_neuron)), decimals=1)

In [14]:
bho = np.round(np.random.uniform(size=(1, outputlayer_neuron)), decimals=1)

In [15]:
who

array([[0.6],
       [0.7]])

In [16]:
bho

array([[0.]])

<img src="../notebooks/images/sigmoid-equation.png" alt="drawing" style="width:150px;"/>

In [17]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [18]:
def derivative_sigmoid(x):
    return x * (1 - x)

In [19]:
# Multiply input with weight matrix (input and hidden layer) and add bias matrix
# apply activation function on weighted input to generate hidden layer activations
# multiply hidden layer activations with weight matrix (hidden and output) and add bias matrix
# Apply activatoin function on weighted hidden layer activations

In [20]:
X.shape, wih.shape

((3, 3), (3, 2))

In [21]:
weighted_input = np.dot(X, wih) + bih

In [22]:
weighted_input.shape

(3, 2)

In [23]:
X

array([[1, 0, 1],
       [1, 1, 1],
       [0, 0, 1]])

In [24]:
wih

array([[0.4, 1. ],
       [0.7, 0.6],
       [0.2, 0.2]])

In [25]:
np.dot(X, wih)

array([[0.6, 1.2],
       [1.3, 1.8],
       [0.2, 0.2]])

In [26]:
1*0.4 + 0*0.7 + 1*0.2

0.6000000000000001

In [27]:
bih

array([[0.1, 0.9]])

In [28]:
bih.shape, np.dot(X, wih).shape

((1, 2), (3, 2))

In [29]:
weighted_input

array([[0.7, 2.1],
       [1.4, 2.7],
       [0.3, 1.1]])

In [30]:
sigmoid(0.7)

0.6681877721681662

In [31]:
sigmoid(2.1)

0.8909031788043871

In [32]:
hiddenlayer_activations = sigmoid(weighted_input)
hiddenlayer_activations

array([[0.66818777, 0.89090318],
       [0.80218389, 0.93702664],
       [0.57444252, 0.75026011]])

In [33]:
weighted_hidden_layer_activation = np.dot(hiddenlayer_activations, who) + bho
output = sigmoid(weighted_hidden_layer_activation)

In [34]:
output

array([[0.73585694],
       [0.75717051],
       [0.70471398]])

![title](../notebooks/images/all_matrices.png)