## Simple Neural Networks in Numpy

In [40]:
import numpy as np

In [41]:
np.random.seed(42)

In [42]:
#Input array
X=np.array([[1,0,1],
            [0,1,1]])

#Output
y=np.array([[1],
            [0]])

In [43]:
X.shape, y.shape

((2, 3), (2, 1))

In [44]:
#Sigmoid Function

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [46]:
#Variable initialization

epoch=5000 #Setting training iterations
lr=10 #Setting learning rate

inputlayer_neurons = X.shape[1] #number of features in data set
hiddenlayer_neurons = 2 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer

In [47]:
#weight and bias initialization

wh=np.round(np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons)), decimals=1)
bh=np.round(np.random.uniform(size=(1,hiddenlayer_neurons)), decimals=1)
wout=np.round(np.random.uniform(size=(hiddenlayer_neurons,output_neurons)), decimals=1)
bout=np.round((np.random.uniform(size=(1,output_neurons))), decimals=1)

In [48]:
wh.shape, bh.shape, wout.shape, bout.shape

((3, 2), (1, 2), (2, 1), (1, 1))

In [50]:
wh

array([[0.4, 1. ],
       [0.7, 0.6],
       [0.2, 0.2]])

In [51]:
bh

array([[0.1, 0.9]])

In [52]:
wout

array([[0.6],
       [0.7]])

In [53]:
bout

array([[0.]])

In [54]:
#Forward Propogation
hidden_layer_input1=np.dot(X,wh)
hidden_layer_input=hidden_layer_input1 + bh

hiddenlayer_activations = sigmoid(hidden_layer_input)

output_layer_input1=np.dot(hiddenlayer_activations,wout)
output_layer_input= output_layer_input1+ bout

output = sigmoid(output_layer_input)

print(output)

[[0.73585694]
 [0.73701465]]


In [55]:
hiddenlayer_activations

array([[0.66818777, 0.89090318],
       [0.73105858, 0.84553473]])

In [56]:
output

array([[0.73585694],
       [0.73701465]])

In [57]:
#Backpropagation
E = y-output

slope_output_layer = derivative_sigmoid(output)
slope_hidden_layer = derivative_sigmoid(hiddenlayer_activations)

d_output = E * slope_output_layer

Error_at_hidden_layer = d_output.dot(wout.T)
d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer

wout += hiddenlayer_activations.T.dot(d_output) *lr
bout += np.sum(d_output, axis=0,keepdims=True) *lr
wh += X.T.dot(d_hiddenlayer) *lr
bh += np.sum(d_hiddenlayer, axis=0,keepdims=True) *lr

In [65]:
E.shape, slope_hidden_layer.shape, slope_output_layer.shape, d_hiddenlayer.shape, d_output.shape, Error_at_hidden_layer.shape

((2, 1), (2, 2), (2, 1), (2, 2), (2, 1), (2, 2))

In [59]:
E

array([[ 0.26414306],
       [-0.73701465]])

In [60]:
slope_hidden_layer

array([[0.22171287, 0.0971947 ],
       [0.19661193, 0.13060575]])

In [61]:
slope_output_layer

array([[0.1943715 ],
       [0.19382405]])

In [62]:
d_output

array([[ 0.05134188],
       [-0.14285117]])

In [63]:
d_hiddenlayer

array([[ 0.00682989,  0.00349311],
       [-0.01685175, -0.01306003]])

In [66]:
Error_at_hidden_layer

array([[ 0.03080513,  0.03593932],
       [-0.0857107 , -0.09999582]])

In [36]:
#Forward Propogation
hidden_layer_input1=np.dot(X,wh)
hidden_layer_input=hidden_layer_input1 + bh

hiddenlayer_activations = sigmoid(hidden_layer_input)

output_layer_input1=np.dot(hiddenlayer_activations,wout)
output_layer_input= output_layer_input1+ bout

output = sigmoid(output_layer_input)

print(output)

[[0.26427653]
 [0.26473829]]


In [37]:
# run for 5000 iterations
for i in range(epoch):

    #Forward Propogation
    hidden_layer_input1=np.dot(X,wh)
    hidden_layer_input=hidden_layer_input1 + bh
    hiddenlayer_activations = sigmoid(hidden_layer_input)
    output_layer_input1=np.dot(hiddenlayer_activations,wout)
    output_layer_input= output_layer_input1+ bout
    output = sigmoid(output_layer_input)

    #Backpropagation
    E = y-output
    slope_output_layer = derivative_sigmoid(output)
    slope_hidden_layer = derivative_sigmoid(hiddenlayer_activations)
    d_output = E * slope_output_layer
    Error_at_hidden_layer = d_output.dot(wout.T)
    d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
    wout += hiddenlayer_activations.T.dot(d_output) *lr
    bout += np.sum(d_output, axis=0,keepdims=True) *lr
    wh += X.T.dot(d_hiddenlayer) *lr
    bh += np.sum(d_hiddenlayer, axis=0,keepdims=True) *lr

print(output)

[[0.99647091]
 [0.00478119]]


## Neural Networks in keras

In [20]:
# import libraries
from keras.layers import Dense
from keras.models import Sequential

Using TensorFlow backend.


In [21]:
model=Sequential()

model.add(Dense(3, input_dim=4, activation='sigmoid'))
model.add(Dense(units=1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer="sgd", metrics=['accuracy'])

In [22]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 3)                 15        
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 4         
Total params: 19
Trainable params: 19
Non-trainable params: 0
_________________________________________________________________


In [23]:
model.fit(X, y, epochs=5000)

ValueError: Error when checking input: expected dense_1_input to have shape (4,) but got array with shape (3,)

In [19]:
loss, accuracy = model.evaluate(X, y)

3/3 [==============================] - 0s 11ms/step


In [20]:
accuracy

1.0